version: "3.8"

services:
  server:
    build:
      context: ./server
    port:
      - 5000:5000

  client:
    build:
      context: ./client
    port:
      - 3000:3000
    depends_on:
      - server
